### ISSUE TITLE
DirectoryNotFoundException

### ISSUE THREAD

**Issue by OmiCron07** [VladPVS/FastSearchLibrary#1]
I get a DirectoryNotFoundException and I think this is because one of the directory or file in the directory make the path longer than ~260 characters Windows limit.

![image](https://user-images.githubusercontent.com/31325575/43734253-2229dcba-9985-11e8-8aae-3c85fec76e7a.png)

Culprit path : "D:\CdProj\Projets\2013\FraLal\13-019  O12-1218-3049 - Cardinal Arena - Cardinal (ext) (près de Ottawa) -  - Ontario - 12 12 3049-0\Plans\Plans Émis pour Construction CAD\13-01-10 ARCHITECTURE pdf\Cardinal Architectural Drawings\Cardinal Architectural Drawings"

**Comment by VladPVS** [comment]
Dear OmiCron07, 
you truly got `DirectoryNotFoundException` due to 260 symbols Windows limit. Most likely you use Visual Studio 2017 and .NET Framework higher than 4.6.2. As I observe, in this case `DirectoryNotFoundException` throws instead `PathTooLongException` but I didn't provide processing the first one. So, I releazed new [version](https://github.com/VladPVS/FastSearchLibrary/releases/tag/v1.1.7) of library, designed specially for VS 2017 users that processes `DirectoryNotFoundException` instead `PathTooLongException`. Moreover, you can execute search in "long" paths too. For this you should add manifest for your project: `<Project name>` -> `right button of mouse` -> `Add` -> `New item` -> `Application manifest file`. Then you should add content of [this](https://github.com/VladPVS/FastSearchLibrary/files/2267462/manifest.txt) file to the manifest before closed tag. The last step is enable long path behavior in Windows. For this you should open registry editor (regedit), go to next path `HKLM\SYSTEM\CurrentControlSet\Control\FileSystem` and create parameter `LongPathsEnabled`  (type REG_DWORD) with `1` value. Computer reboot may be necessary.

**Comment by OmiCron07** [comment]
Thank you for the quick fix. 

But it seems you locked down the lib to 4.7.2 and higher. Should not be preferable to keep the .Net version requirement as low as possible and only adding the catch DirectoryNotFoundException after the catch PathTooLongException?

**Comment by VladPVS** [comment]
As I understand `DirectoryNotFoundException` occurrs instead `PathTooLongException` in higher versions of .NET Framework (4.6.2 and higher). I have tested it on VS2015 and VS2017. I have reduced the required version of .NET to 4.6.2 in v1.1.7.1. It is necessary minimum to have possibility of working with long paths. And I have combined `DirectoryNotFoundException` and `PathTooLongException` in v1.1.7.2. But I can make searching to work with "long" paths only when I compile program that uses this library in VS2017. In VS2015 the same program ignores "long" paths. Therefore if you want to execute search in "long" paths too you probably should write program using VS2017.
